version: '3.8'
services:
  db:
    image: postgres:15
    container_name: se302_db
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fullstack_kristin_project
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: